import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../data/database/app_database.dart';
import '../data/repositories/task_repository.dart';
import '../services/auto_task_generator_service.dart';
import 'database_provider.dart';
import 'current_event_provider.dart';
import 'participant_provider.dart';
import 'expense_provider.dart';
import 'payment_provider.dart';
import 'income_provider.dart';
import 'role_provider.dart';
import 'family_provider.dart';
import 'ruleset_provider.dart';

/// Provider for TaskRepository
final taskRepositoryProvider = Provider<TaskRepository>((ref) {
  final database = ref.watch(databaseProvider);
  return TaskRepository(database);
});

/// Provider for watching tasks for the current event
final tasksProvider = StreamProvider<List<Task>>((ref) {
  final repository = ref.watch(taskRepositoryProvider);
  final currentEvent = ref.watch(currentEventProvider);

  if (currentEvent == null) {
    return Stream.value([]);
  }

  return repository.watchTasksByEvent(currentEvent.id);
});

/// Provider for getting a single task by ID
final taskByIdProvider = FutureProvider.family<Task?, int>((ref, id) async {
  final repository = ref.watch(taskRepositoryProvider);
  return repository.getTaskById(id);
});

/// Provider for task statistics
final taskStatisticsProvider = FutureProvider<Map<String, dynamic>>((ref) async {
  final repository = ref.watch(taskRepositoryProvider);
  final currentEvent = ref.watch(currentEventProvider);

  if (currentEvent == null) {
    return {
      'total': 0,
      'pending': 0,
      'inProgress': 0,
      'completed': 0,
      'overdue': 0,
      'completionRate': 0.0,
    };
  }

  return repository.getTaskStatistics(currentEvent.id);
});

/// Provider for overdue tasks
final overdueTasksProvider = FutureProvider<List<Task>>((ref) async {
  final repository = ref.watch(taskRepositoryProvider);
  final currentEvent = ref.watch(currentEventProvider);

  if (currentEvent == null) {
    return [];
  }

  return repository.getOverdueTasks(currentEvent.id);
});

/// Provider for upcoming tasks
final upcomingTasksProvider = FutureProvider<List<Task>>((ref) async {
  final repository = ref.watch(taskRepositoryProvider);
  final currentEvent = ref.watch(currentEventProvider);

  if (currentEvent == null) {
    return [];
  }

  return repository.getUpcomingTasks(currentEvent.id);
});

// ============================================================================
// AUTO TASK GENERATION PROVIDERS
// ============================================================================

/// Provider for AutoTaskGeneratorService
final autoTaskGeneratorServiceProvider = Provider<AutoTaskGeneratorService>((ref) {
  final database = ref.watch(databaseProvider);
  final participantRepo = ref.watch(participantRepositoryProvider);
  final expenseRepo = ref.watch(expenseRepositoryProvider);
  final paymentRepo = ref.watch(paymentRepositoryProvider);
  final incomeRepo = ref.watch(incomeRepositoryProvider);
  final roleRepo = ref.watch(roleRepositoryProvider);
  final familyRepo = ref.watch(familyRepositoryProvider);
  final taskRepo = ref.watch(taskRepositoryProvider);
  final rulesetRepo = ref.watch(rulesetRepositoryProvider);

  return AutoTaskGeneratorService(
    database: database,
    participantRepo: participantRepo,
    expenseRepo: expenseRepo,
    paymentRepo: paymentRepo,
    incomeRepo: incomeRepo,
    roleRepo: roleRepo,
    familyRepo: familyRepo,
    taskRepo: taskRepo,
    rulesetRepo: rulesetRepo,
  );
});

/// Provider for auto-generated tasks
final autoGeneratedTasksProvider =
    FutureProvider<Map<String, List<GeneratedTask>>>((ref) async {
  final service = ref.watch(autoTaskGeneratorServiceProvider);
  final currentEvent = ref.watch(currentEventProvider);

  if (currentEvent == null) {
    return {};
  }

  return service.generateAllTasks(currentEvent.id, currentEvent);
});

/// Provider for overdue auto tasks count (for badge)
final overdueAutoTasksCountProvider = FutureProvider<int>((ref) async {
  final repository = ref.watch(taskRepositoryProvider);
  final currentEvent = ref.watch(currentEventProvider);

  if (currentEvent == null) {
    return 0;
  }

  return repository.getOverdueAutoTasksCount(currentEvent.id);
});
